project:
    type: website

execute:
    freeze: auto

website:
    title: "pyobsplot"
    site-url: "https://juba.github.io/pyobsplot"
    favicon: favicon.png
    repo-url: https://github.com/juba/pyobsplot/
    repo-subdir: "doc"
    repo-actions: [issue]
    page-navigation: true
    search:
        location: navbar
        type: overlay
    navbar:
        background: "#e15759"
        pinned: false
        left:
            - text: "Documentation"
              href: getting_started.qmd
            - changelog.md
        tools:
            - icon: github
              href: https://github.com/juba/pyobsplot/
    sidebar:
        - title: "Documentation"
          style: "floating"
          contents:
              - section: "Usage"
                contents:
                    - getting_started.qmd
                    - usage.qmd
              - section: "Gallery"
                contents:
                    - gallery_marks.qmd
                    - gallery_transforms.qmd
                    - gallery_geo.qmd
                    - gallery_interaction.qmd
                    - gallery_themes.qmd
              - section: "Development"
                contents:
                    - development.qmd

format:
    html:
        theme:
            - cosmo
            - custom.scss
        mainfont: "'Source Sans 3', 'Source Sans Pro', 'Segoe UI', 'Roboto', 'Helvetica', sans-serif"
        monofont: "Fira Mono"
        linkcolor: "#FF4222"
        toc: true
        highlight-style: gruvbox
        grid:
            body-width: 900px
            gutter-width: 3rem
